// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using RouteAPI.Models;
using System;

namespace RouteAPI.Migrations
{
    [DbContext(typeof(RouteAPIContext))]
    [Migration("20180321175044_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RouteAPI.Models.Checkpoint", b =>
                {
                    b.Property<int>("CheckpointID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CPDateTime");

                    b.Property<string>("Latitude");

                    b.Property<string>("Longitude");

                    b.Property<int>("RouteID");

                    b.HasKey("CheckpointID");

                    b.ToTable("Checkpoint");
                });
#pragma warning restore 612, 618
        }
    }
}
